openapi: 3.0.0
info:
  title: Banner API
  description: API endpoints for managing banners
  version: 1.0.0
tags:
  - name: Banner
    description: API for banner management
paths:
  /api/banners:
    get:
      summary: Get a list of all banners
      tags:
        - Banner
      responses:
        200:
          description: A list of banners
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 60f5b5f5c5b3c3a6b4f5d5c5
                    title:
                      type: string
                      example: "Summer Hits"
                    imageUrl:
                      type: string
                      example: "https://example.com/banner.jpg"
                    linkTo:
                      type: string
                      example: "/song/123"
                    isActive:
                      type: boolean
                      example: true

    post:
      summary: Create a new banner
      tags:
        - Banner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Summer Hits"
                imageUrl:
                  type: string
                  example: "https://example.com/banner.jpg"
                linkTo:
                  type: string
                  example: "/song/123"
                isActive:
                  type: boolean
                  example: true
      responses:
        201:
          description: Banner created successfully
        400:
          description: Bad request

  /api/banners/{id}:
    get:
      summary: Get banner details by ID
      tags:
        - Banner
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the banner
          schema:
            type: string
            example: 60f5b5f5c5b3c3a6b4f5d5c5
      responses:
        200:
          description: Banner details
        404:
          description: Banner not found

    put:
      summary: Update a banner by ID
      tags:
        - Banner
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the banner to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Updated Banner Title"
                imageUrl:
                  type: string
                  example: "https://example.com/new-banner.jpg"
                linkTo:
                  type: string
                  example: "/song/456"
                isActive:
                  type: boolean
                  example: fa
